language: node_js
node_js:
  - "6"
before_install:
  - npm install -g bower pulp purescript
install:
  - npm install
  - bower install
script:
  - pulp build
  - pulp test
after_success:
  - >-
    test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
