language: node_js
node_js:
  - node
install:
  - npm install
  - npm run-script psc-package install
script:
  - npm run-script build
  - npm test
after_success:
  - >-
    test $TRAVIS_TAG &&
    echo $GITHUB_TOKEN | pulp login &&
    echo y | pulp publish --no-push
branches:
  only:
    - master
    - /^v[0-9]+\.[0-9]+\.[0-9]+$/
